### ISSUE TITLE
Hex grid mangled after translation

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#245]
Several events have Google Translate embedded, which when active funks up the hex grid. This might be also affecting users with certain web-browsers or extensions. The bug is only visual, it does not affect the ability to explore projects. In any case we should be able to continue using the Google Translate tool with dribdat. See screenshot:

![Screenshot from 2021-05-12 11-13-29](https://user-images.githubusercontent.com/31819/117950212-3e8b5000-b313-11eb-8ccf-29752ac53c31.png)

Introduced in the UX changes in #243

**Comment by loleg** [comment]
This was just an issue with the local setting. The old layout required this CSS, which when taken out fixed the issue:

```css
html .hexagontent { position: relative; }
html:lang(en) .hexagontent { position: absolute; }
```
