### ISSUE TITLE
Trim event branding from user screens

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#255]
The login, registration and user profile screens do not need the headers and titles of the event. It gets particularly confusing when parallel events are running on the same server. Site owners could still override this with their event or institution logo using the server-side setting.

As a quick workaround, this custom stylesheet can be used:

```css
.userform .navbar-nav.nav-fill,
.userprofile .section.section-centered.section-header,
.userform .section.section-centered.section-header { display: none; }
.userform .container.event-header {
    background: url(https://dribdat.cc/logo11.png) no-repeat;
    background-size: contain; width: 100%; height: 128px;
}
```
